#[derive(Clone, Copy)]
pub(crate) struct NamedColor {
    pub name: &'static str,
    pub red: u8,
    pub green: u8,
    pub blue: u8,
}

pub(crate) const NAMED_COLORS: &[NamedColor] = &[
    NamedColor {
        name: "AliceBlue",
        red: 240,
        green: 248,
        blue: 255,
    },
    NamedColor {
        name: "AntiqueWhite",
        red: 250,
        green: 235,
        blue: 215,
    },
    NamedColor {
        name: "Aqua",
        red: 0,
        green: 255,
        blue: 255,
    },
    NamedColor {
        name: "Aquamarine",
        red: 127,
        green: 255,
        blue: 212,
    },
    NamedColor {
        name: "Azure",
        red: 240,
        green: 255,
        blue: 255,
    },
    NamedColor {
        name: "Beige",
        red: 245,
        green: 245,
        blue: 220,
    },
    NamedColor {
        name: "Bisque",
        red: 255,
        green: 228,
        blue: 196,
    },
    NamedColor {
        name: "Black",
        red: 0,
        green: 0,
        blue: 0,
    },
    NamedColor {
        name: "BlanchedAlmond",
        red: 255,
        green: 235,
        blue: 205,
    },
    NamedColor {
        name: "Blue",
        red: 0,
        green: 0,
        blue: 255,
    },
    NamedColor {
        name: "BlueViolet",
        red: 138,
        green: 43,
        blue: 226,
    },
    NamedColor {
        name: "Brown",
        red: 165,
        green: 42,
        blue: 42,
    },
    NamedColor {
        name: "Burlywood",
        red: 222,
        green: 184,
        blue: 135,
    },
    NamedColor {
        name: "CadetBlue",
        red: 95,
        green: 158,
        blue: 160,
    },
    NamedColor {
        name: "Chartreuse",
        red: 127,
        green: 255,
        blue: 0,
    },
    NamedColor {
        name: "Chocolate",
        red: 210,
        green: 105,
        blue: 30,
    },
    NamedColor {
        name: "Coral",
        red: 255,
        green: 127,
        blue: 80,
    },
    NamedColor {
        name: "CornflowerBlue",
        red: 100,
        green: 149,
        blue: 237,
    },
    NamedColor {
        name: "Cornsilk",
        red: 255,
        green: 248,
        blue: 220,
    },
    NamedColor {
        name: "Crimson",
        red: 220,
        green: 20,
        blue: 60,
    },
    NamedColor {
        name: "Cyan",
        red: 0,
        green: 255,
        blue: 255,
    },
    NamedColor {
        name: "DarkBlue",
        red: 0,
        green: 0,
        blue: 139,
    },
    NamedColor {
        name: "DarkCyan",
        red: 0,
        green: 139,
        blue: 139,
    },
    NamedColor {
        name: "DarkGoldenrod",
        red: 184,
        green: 134,
        blue: 11,
    },
    NamedColor {
        name: "DarkGray",
        red: 169,
        green: 169,
        blue: 169,
    },
    NamedColor {
        name: "DarkGreen",
        red: 0,
        green: 100,
        blue: 0,
    },
    NamedColor {
        name: "DarkGrey",
        red: 169,
        green: 169,
        blue: 169,
    },
    NamedColor {
        name: "DarkKhaki",
        red: 189,
        green: 183,
        blue: 107,
    },
    NamedColor {
        name: "DarkMagenta",
        red: 139,
        green: 0,
        blue: 139,
    },
    NamedColor {
        name: "DarkOliveGreen",
        red: 85,
        green: 107,
        blue: 47,
    },
    NamedColor {
        name: "DarkOrange",
        red: 255,
        green: 140,
        blue: 0,
    },
    NamedColor {
        name: "DarkOrchid",
        red: 153,
        green: 50,
        blue: 204,
    },
    NamedColor {
        name: "DarkRed",
        red: 139,
        green: 0,
        blue: 0,
    },
    NamedColor {
        name: "DarkSalmon",
        red: 233,
        green: 150,
        blue: 122,
    },
    NamedColor {
        name: "DarkSeaGreen",
        red: 143,
        green: 188,
        blue: 143,
    },
    NamedColor {
        name: "DarkSlateBlue",
        red: 72,
        green: 61,
        blue: 139,
    },
    NamedColor {
        name: "DarkSlateGray",
        red: 47,
        green: 79,
        blue: 79,
    },
    NamedColor {
        name: "DarkSlateGrey",
        red: 47,
        green: 79,
        blue: 79,
    },
    NamedColor {
        name: "DarkTurquoise",
        red: 0,
        green: 206,
        blue: 209,
    },
    NamedColor {
        name: "DarkViolet",
        red: 148,
        green: 0,
        blue: 211,
    },
    NamedColor {
        name: "DeepPink",
        red: 255,
        green: 20,
        blue: 147,
    },
    NamedColor {
        name: "DeepSkyBlue",
        red: 0,
        green: 191,
        blue: 255,
    },
    NamedColor {
        name: "DimGray",
        red: 105,
        green: 105,
        blue: 105,
    },
    NamedColor {
        name: "DimGrey",
        red: 105,
        green: 105,
        blue: 105,
    },
    NamedColor {
        name: "DodgerBlue",
        red: 30,
        green: 144,
        blue: 255,
    },
    NamedColor {
        name: "Firebrick",
        red: 178,
        green: 34,
        blue: 34,
    },
    NamedColor {
        name: "FloralWhite",
        red: 255,
        green: 250,
        blue: 240,
    },
    NamedColor {
        name: "ForestGreen",
        red: 34,
        green: 139,
        blue: 34,
    },
    NamedColor {
        name: "Fuchsia",
        red: 255,
        green: 0,
        blue: 255,
    },
    NamedColor {
        name: "Gainsboro",
        red: 220,
        green: 220,
        blue: 220,
    },
    NamedColor {
        name: "GhostWhite",
        red: 248,
        green: 248,
        blue: 255,
    },
    NamedColor {
        name: "Gold",
        red: 255,
        green: 215,
        blue: 0,
    },
    NamedColor {
        name: "Goldenrod",
        red: 218,
        green: 165,
        blue: 32,
    },
    NamedColor {
        name: "Gray",
        red: 128,
        green: 128,
        blue: 128,
    },
    NamedColor {
        name: "Green",
        red: 0,
        green: 128,
        blue: 0,
    },
    NamedColor {
        name: "GreenYellow",
        red: 173,
        green: 255,
        blue: 47,
    },
    NamedColor {
        name: "Grey",
        red: 128,
        green: 128,
        blue: 128,
    },
    NamedColor {
        name: "Honeydew",
        red: 240,
        green: 255,
        blue: 240,
    },
    NamedColor {
        name: "Hotpink",
        red: 255,
        green: 105,
        blue: 180,
    },
    NamedColor {
        name: "IndianRed",
        red: 205,
        green: 92,
        blue: 92,
    },
    NamedColor {
        name: "Indigo",
        red: 75,
        green: 0,
        blue: 130,
    },
    NamedColor {
        name: "Ivory",
        red: 255,
        green: 255,
        blue: 240,
    },
    NamedColor {
        name: "Khaki",
        red: 240,
        green: 230,
        blue: 140,
    },
    NamedColor {
        name: "Lavender",
        red: 230,
        green: 230,
        blue: 250,
    },
    NamedColor {
        name: "LavenderBlush",
        red: 255,
        green: 240,
        blue: 245,
    },
    NamedColor {
        name: "LawnGreen",
        red: 124,
        green: 252,
        blue: 0,
    },
    NamedColor {
        name: "LemonChiffon",
        red: 255,
        green: 250,
        blue: 205,
    },
    NamedColor {
        name: "LightBlue",
        red: 173,
        green: 216,
        blue: 230,
    },
    NamedColor {
        name: "LightCoral",
        red: 240,
        green: 128,
        blue: 128,
    },
    NamedColor {
        name: "LightCyan",
        red: 224,
        green: 255,
        blue: 255,
    },
    NamedColor {
        name: "LightGoldenrodYellow",
        red: 250,
        green: 250,
        blue: 210,
    },
    NamedColor {
        name: "LightGray",
        red: 211,
        green: 211,
        blue: 211,
    },
    NamedColor {
        name: "LightGreen",
        red: 144,
        green: 238,
        blue: 144,
    },
    NamedColor {
        name: "LightGrey",
        red: 211,
        green: 211,
        blue: 211,
    },
    NamedColor {
        name: "LightPink",
        red: 255,
        green: 182,
        blue: 193,
    },
    NamedColor {
        name: "LightSalmon",
        red: 255,
        green: 160,
        blue: 122,
    },
    NamedColor {
        name: "LightSeaGreen",
        red: 32,
        green: 178,
        blue: 170,
    },
    NamedColor {
        name: "LightSkyBlue",
        red: 135,
        green: 206,
        blue: 250,
    },
    NamedColor {
        name: "LightSlateGray",
        red: 119,
        green: 136,
        blue: 153,
    },
    NamedColor {
        name: "LightSlateGrey",
        red: 119,
        green: 136,
        blue: 153,
    },
    NamedColor {
        name: "LightSteelBlue",
        red: 176,
        green: 196,
        blue: 222,
    },
    NamedColor {
        name: "LightYellow",
        red: 255,
        green: 255,
        blue: 224,
    },
    NamedColor {
        name: "Lime",
        red: 0,
        green: 255,
        blue: 0,
    },
    NamedColor {
        name: "LimeGreen",
        red: 50,
        green: 205,
        blue: 50,
    },
    NamedColor {
        name: "Linen",
        red: 250,
        green: 240,
        blue: 230,
    },
    NamedColor {
        name: "Magenta",
        red: 255,
        green: 0,
        blue: 255,
    },
    NamedColor {
        name: "Maroon",
        red: 128,
        green: 0,
        blue: 0,
    },
    NamedColor {
        name: "MediumAquamarine",
        red: 102,
        green: 205,
        blue: 170,
    },
    NamedColor {
        name: "MediumBlue",
        red: 0,
        green: 0,
        blue: 205,
    },
    NamedColor {
        name: "MediumOrchid",
        red: 186,
        green: 85,
        blue: 211,
    },
    NamedColor {
        name: "MediumPurple",
        red: 147,
        green: 112,
        blue: 219,
    },
    NamedColor {
        name: "MediumSeaGreen",
        red: 60,
        green: 179,
        blue: 113,
    },
    NamedColor {
        name: "MediumSlateBlue",
        red: 123,
        green: 104,
        blue: 238,
    },
    NamedColor {
        name: "MediumSpringGreen",
        red: 0,
        green: 250,
        blue: 154,
    },
    NamedColor {
        name: "MediumTurquoise",
        red: 72,
        green: 209,
        blue: 204,
    },
    NamedColor {
        name: "MediumVioletRed",
        red: 199,
        green: 21,
        blue: 133,
    },
    NamedColor {
        name: "MidnightBlue",
        red: 25,
        green: 25,
        blue: 112,
    },
    NamedColor {
        name: "MintCream",
        red: 245,
        green: 255,
        blue: 250,
    },
    NamedColor {
        name: "MistyRose",
        red: 255,
        green: 228,
        blue: 225,
    },
    NamedColor {
        name: "Moccasin",
        red: 255,
        green: 228,
        blue: 181,
    },
    NamedColor {
        name: "NavajoWhite",
        red: 255,
        green: 222,
        blue: 173,
    },
    NamedColor {
        name: "Navy",
        red: 0,
        green: 0,
        blue: 128,
    },
    NamedColor {
        name: "OldLace",
        red: 253,
        green: 245,
        blue: 230,
    },
    NamedColor {
        name: "Olive",
        red: 128,
        green: 128,
        blue: 0,
    },
    NamedColor {
        name: "OliveDrab",
        red: 107,
        green: 142,
        blue: 35,
    },
    NamedColor {
        name: "Orange",
        red: 255,
        green: 165,
        blue: 0,
    },
    NamedColor {
        name: "OrangeRed",
        red: 255,
        green: 69,
        blue: 0,
    },
    NamedColor {
        name: "Orchid",
        red: 218,
        green: 112,
        blue: 214,
    },
    NamedColor {
        name: "PaleGoldenrod",
        red: 238,
        green: 232,
        blue: 170,
    },
    NamedColor {
        name: "PaleGreen",
        red: 152,
        green: 251,
        blue: 152,
    },
    NamedColor {
        name: "PaleTurquoise",
        red: 175,
        green: 238,
        blue: 238,
    },
    NamedColor {
        name: "PaleVioletred",
        red: 219,
        green: 112,
        blue: 147,
    },
    NamedColor {
        name: "PapayaWhip",
        red: 255,
        green: 239,
        blue: 213,
    },
    NamedColor {
        name: "PeachPuff",
        red: 255,
        green: 218,
        blue: 185,
    },
    NamedColor {
        name: "Peru",
        red: 205,
        green: 133,
        blue: 63,
    },
    NamedColor {
        name: "Pink",
        red: 255,
        green: 192,
        blue: 203,
    },
    NamedColor {
        name: "Plum",
        red: 221,
        green: 160,
        blue: 221,
    },
    NamedColor {
        name: "PowderBlue",
        red: 176,
        green: 224,
        blue: 230,
    },
    NamedColor {
        name: "Purple",
        red: 128,
        green: 0,
        blue: 128,
    },
    NamedColor {
        name: "Red",
        red: 255,
        green: 0,
        blue: 0,
    },
    NamedColor {
        name: "RosyBrown",
        red: 188,
        green: 143,
        blue: 143,
    },
    NamedColor {
        name: "RoyalBlue",
        red: 65,
        green: 105,
        blue: 225,
    },
    NamedColor {
        name: "SaddleBrown",
        red: 139,
        green: 69,
        blue: 19,
    },
    NamedColor {
        name: "Salmon",
        red: 250,
        green: 128,
        blue: 114,
    },
    NamedColor {
        name: "SandyBrown",
        red: 244,
        green: 164,
        blue: 96,
    },
    NamedColor {
        name: "SeaGreen",
        red: 46,
        green: 139,
        blue: 87,
    },
    NamedColor {
        name: "SeaShell",
        red: 255,
        green: 245,
        blue: 238,
    },
    NamedColor {
        name: "Sienna",
        red: 160,
        green: 82,
        blue: 45,
    },
    NamedColor {
        name: "Silver",
        red: 192,
        green: 192,
        blue: 192,
    },
    NamedColor {
        name: "SkyBlue",
        red: 135,
        green: 206,
        blue: 235,
    },
    NamedColor {
        name: "SlateBlue",
        red: 106,
        green: 90,
        blue: 205,
    },
    NamedColor {
        name: "SlateGray",
        red: 112,
        green: 128,
        blue: 144,
    },
    NamedColor {
        name: "SlateGrey",
        red: 112,
        green: 128,
        blue: 144,
    },
    NamedColor {
        name: "Snow",
        red: 255,
        green: 250,
        blue: 250,
    },
    NamedColor {
        name: "SpringGreen",
        red: 0,
        green: 255,
        blue: 127,
    },
    NamedColor {
        name: "SteelBlue",
        red: 70,
        green: 130,
        blue: 180,
    },
    NamedColor {
        name: "Tan",
        red: 210,
        green: 180,
        blue: 140,
    },
    NamedColor {
        name: "Teal",
        red: 0,
        green: 128,
        blue: 128,
    },
    NamedColor {
        name: "Thistle",
        red: 216,
        green: 191,
        blue: 216,
    },
    NamedColor {
        name: "Tomato",
        red: 255,
        green: 99,
        blue: 71,
    },
    NamedColor {
        name: "Turquoise",
        red: 64,
        green: 224,
        blue: 208,
    },
    NamedColor {
        name: "Violet",
        red: 238,
        green: 130,
        blue: 238,
    },
    NamedColor {
        name: "Wheat",
        red: 245,
        green: 222,
        blue: 179,
    },
    NamedColor {
        name: "White",
        red: 255,
        green: 255,
        blue: 255,
    },
    NamedColor {
        name: "WhiteSmoke",
        red: 245,
        green: 245,
        blue: 245,
    },
    NamedColor {
        name: "Yellow",
        red: 255,
        green: 255,
        blue: 0,
    },
    NamedColor {
        name: "YellowGreen",
        red: 154,
        green: 205,
        blue: 50,
    },
];
